version: '3'
services:
  go:
    container_name: "grd1_go"
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"
    command: air
    networks:
      - grd1-network
    links:
      - "rabbitmq"
    env_file:
      .env

  rabbitmq:
    image: "rabbitmq:3-management"
    restart: unless-stopped
    hostname: "rabbitmq"
    container_name: "grd1_amqp"
    environment:
      RABBITMQ_ERLANG_COOKIE: "BUDJY4HKWCB5DNPS9792"
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "root"
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    ports:
      - "8373:15672"
      - "8372:5672"
    networks:
      - grd1-network
    tty: true
    command: bash -c "rabbitmq-plugins enable rabbitmq_management; rabbitmq-server;"
    expose:
      - '8373'
      - '8372'

networks:
  grd1-network:
    driver: bridge